### ISSUE TITLE
Ceph Validator

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#225]
In order to verify deployed ceph enviroments a validation mechanism is needed.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

It is being validated that:

- [x] Number of cephs mons are equal to what is configured
- [x] Ceph mons have quorum
- [x] Health is acceptable
- [x] Number of ceph managers are equal to what is configured
- [x] Ceph mgr modules are active as per configuration
- [x] Number of OSDs are equal to configuration
- [x] OSDs are up and in
- [x] All acceptance criteria are met
- [x] Changes have been reviewed
- [x] CI tests have run successfully
- [x] Documentation has been updated
- [x] Release Notes have been updated

**Comment by master-caster** [comment]
I'm currently in the process of installation so there are some questions coming up for me.
One Question is: do a fresh ceph install or use the existing ceph that is than connected as "external" Ceph cluster
to the infrastructure.

The reason why i wrote this is, i don't think that the definition of done parameter like "Number of OSDs are equal to configuration" fits to an installation using an existing ceph cluster.

Or is there a documented way to describe already existing ceph cluster in a way that it gets manageable?
I doubt this since there is probably no support, for example, for LXC based ceph installations which
could be used by ceph-ansible.

Maybe this case is out of scope .... in this case never mind :grin:

**Comment by fkr** [comment]
https://github.com/osism/ansible-collection-validations

**Comment by fkr** [comment]
@master-caster as discussed in todays IaaS Sprint Review as part of this story, the scope of this story is to assure that a deployment that was done via osism has been properly deployed.

**Comment by garloff** [comment]
PR exists, work is 90% complete, tests are there.
`osism validate` command is still to be done (old `osism-validate` already works).
Then merge.

**Comment by ppkuschy** [comment]
> PR exists, work is 90% complete, tests are there. `osism validate` command is still to be done (old `osism-validate` already works). Then merge.

Correction: So far only the PR for ceph-mons exists, ceph-mgrs will follow today and ceph-osds will take a few more days. Also the playbooks will be migrated into roles later on. But at least one can validate ceph-mons already.

**Comment by fkr** [comment]
All agreed-on functionality has been implemented.
Release notes mention it, but could be more emphasized.

Documentation pending.

**Comment by fkr** [comment]
Docs are here: https://github.com/osism/documentation/pull/466
