### ISSUE TITLE
Clear requirements for dns names for SCS zuul infrastructure

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#242]
We need to make sure to have all proper dns name requirements cleared. We should check with @itrich and @garloff on the dns names and records that need to be created for the zuul infrastructure.

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by o-otte** [comment]
I checked the OSISM Ansible Role for Zuul and they use two domains related to the Zuul Deployment. One for the Web Frontend and one for Logs.

So we need two domains named zuul.* and log.* on an SCS-Domain. I don't know which SCS Domain to use for Zuul. Maybe zuul.scs.community? @garloff and @itrich, do you have any domain in mind for which we can add the zuul subdomains to?

@master-caster FYI

**Comment by fkr** [comment]
Feedback from SIG Community: We should see that everything is in the scs.community namespace.
@garloff is the one who can create dns records.

**Comment by master-caster** [comment]
OSISM Zuul role would like to use proper certificates. In the time being I may use snake oil certificates to go on with zuul.

As I don't know whats comming next I would prefer something like zuul.* and zuul-log.* 
Do we need to do anything here, or is it just waiting until domains are available?

**Comment by o-otte** [comment]
@garloff @fkr, as @master-caster wrote, we need those domains to continue:
* zuul.scs.community
* zuul-logs.scs.community

We also need proper certificates. How are we getting those? As far as I see Let's Encrypt is used for scs.community. So something like the Ansible [community.crypto.acme_certificate](https://docs.ansible.com/ansible/latest/collections/community/crypto/acme_certificate_module.html) module could be used, couldn't it?

**Comment by garloff** [comment]
Tell me the IP addresses and I'll get you the A records for them.
As controller of the server, you can obviously get yourself LE certs. On k8s you would deploy cert-manager, I guess. Or you use a caddy container (ask @itrich).
As controller of the domain I could also create LE certs for you, but I would prefer not to.

Sidenote: We have other domains as well, but if this ends up being the official zuul for our community, then .scs.community is the right one to use.

**Comment by master-caster** [comment]
The current working node is reachable at `31.172.116.118`. For now i would stay with one IP address.
Nodepool will probably use a second node but AFAIK it is not necessary to have a name for it.

Since we need two FQDN I recommend to use a CNAME as Jens stated out OSISM is also creating a SAN for Zuul.

zuul.scs.community -> Domain name
zuul-logs.scs.community -> CNAME -> zuul.scs.community

**Comment by garloff** [comment]
Done.
Let me know if something does not work.

**Comment by master-caster** [comment]
Test installation is accessible through DNS Names.

**Comment by master-caster** [comment]
With DNS in place we can proceed here. To be as self contained as possible I would like to create an virtual environment.
On the other hand it looks like it is not possible to switch to this virtual environment the current running playbook.

Anyone with a solution or an opinion on this?

**Comment by master-caster** [comment]
As the progress is going on on the playbook there are some key aspects we might have to discuss.
For now the question is, how to use Let's encrypt?
Basically I think there are three possible challenges to acquire a valid certificate.
1. HTTP
2. DNS
3. TLS-ALPN (not recommended for most use cases by documentation)

In my opinion we should stay with `HTTP`. If desired, we might use the DNS challenge. But I don't
know if we could do this with our DNS (OSISM is using DNS afaik). 
@garloff Do you know if this is possible with a meaningful amount of efforts?

Right now the playbook is build assuming using HTTP challenge is a valid choice. Due to the nature of the
HTTP mechanism we need an instance providing the challenge that will be verified.
For this purpose I would consider a reverse proxy that handles the ACME challenge and otherwise it
forwards to our Zuul instance.

Since the OSISM Zuul role is creating / installing containerized Zuul I would use some ready to use
containers providing reverse proxy functionality combined with auto renewal for our certificates.

Any thoughts on this? @fkr @osfrickler

**Comment by itrich** [comment]
> Right now the playbook is build assuming using HTTP challenge is a valid choice. Due to the nature of the HTTP mechanism we need an instance providing the challenge that will be verified. For this purpose I would consider a reverse proxy that handles the ACME challenge and otherwise it forwards to our Zuul instance.

I have made very good experiences with [Caddy](https://caddyserver.com/), which fulfills exactly the above described use-case.

> Since the OSISM Zuul role is creating / installing containerized Zuul I would use some ready to use containers providing reverse proxy functionality combined with auto renewal for our certificates.

I can recommend the containerized version by @lucaslorentz: https://github.com/lucaslorentz/caddy-docker-proxy

Don't hesitate to contact me if you have any questions on the above projects.

**Comment by berendt** [comment]
For LE we are using DNS AUTH01 with the help of the Lego client and Designate as DNSaaS.

**Comment by fkr** [comment]
Yeah, if http for LE is chosen, I'd also opt for the caddy-way that @itrich proposed.
If nginx is desired, [this](https://g.hazardous.org/fkr/ansible-nginx-letsencrypt) could proof useful.

**Comment by osfrickler** [comment]
I'm not sure if this discussion still matches the issue or whether it would be better to create a new one.

Our implementation already uses a httpd container that serves the log files and proxies the zuul web interface. IMO instead of adding yet another proxy in front of it, we should look for a solution that either amends this container with an LE component or replace it with a container that can do everything.

**Comment by osfrickler** [comment]
The other issue to consider is a possible future extension to have a HA-capable installation that may run distributed onto multiple servers running possibly on multiple clouds. It should still be possible to have consistent cert generation in that case and I'm not sure how that can be achieved with the HTTP-01 path.

**Comment by garloff** [comment]
The DNS records for this are currently managed in my personal account on OTC (which has a RESAT API that is almost compatible with designate, sigh!). To avoid sharing the secret to manage all records there, we'd need to build a simple service that authenticates requests for changes to _acme-challenge.zuul.scs.community and then performs them.
Doing it manually every three months is possible, but can quickly become annoying.

**Comment by osfrickler** [comment]
You can use CNAME records to delegate the auth process to any other zone, which can then be hosted somewhere else, like on a proper Designate installation. We do the same in opendev, see e.g. https://opendev.org/opendev/zone-opendev.org/src/branch/master/zones/opendev.org/zone.db#L20. Could even be `acme.scs.community`.
