### ISSUE TITLE
Inter SCS cloud migration

### ISSUE THREAD

**Issue by tibeer** [SovereignCloudStack/issues#310]
As a consumer of a SCS based cloud, I want be able to migrate my workload from one SCS cloud to another.
For the moment we will focus on a PoC what will allow the migration of a single VM. The tasks of this will be handled by a microservice architecture we need to develop. We also need to look into <https://github.com/os-migrate/os-migrate>

## Definition of Ready:

- [x] User Story is small enough to be finished within one sprint
- [x] User Story is clear and understood by the whole team
- [x] Acceptance criteria are defined
- [x] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] Minimal required set of features are gathered in some sort of document publicly available
- [x] PoC has been created
- [ ] PoC has the minimal set of required features
- [ ] PoC is working
- [ ] PoC is running on a daily basis with a status report publicly visible (status badge or similar)
- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by fkr** [comment]
Imho this needs some more refinement, as 'one SCS cloud to another' is not specific enough. Is this on the IaaS level? are we talking containers that are orchestrated via cluster api?

**Comment by tibeer** [comment]
> Imho this needs some more refinement, as 'one SCS cloud to another' is not specific enough. Is this on the IaaS level? are we talking containers that are orchestrated via cluster api?

Added some more information. The refined story will be available after the first hacking session.

**Comment by tibeer** [comment]
Current status: os-migrate/os-migrate project looks promising, but you have to use old libraries. And it seems that a migration between public clouds often ends up stuck. Upstream requests made: https://github.com/os-migrate/os-migrate/issues/606

**Comment by tibeer** [comment]
os-migrate/os-migrate is unfortunately (currently) incapable of migrating between two clouds that do not share a certain amount of network infrastructure. This is something, that needs to be debugged (according to their comments).

**Comment by fkr** [comment]
@alexander-diab what has happend to the inter-cloud migration poc? Can you shed some light on the outcomes?

**Comment by alexander-diab** [comment]
Tims effort have not been followed after he has left OSISM. 
After that Matthias Fechner has demonstrated a simpler mvp of migrating solutions between two cloud environments by simply downloading and uploading vm images. This has been documented. 

I will close this issue for now, partly because I do not see any ressource, that can pick this up. 

Nonetheless, I believe that a technical Proof-Of-Concept, which can demonstrate the interoperability capability  of SCS, would be very beneficial and should be part of our pitching toolset. For that matter I would advise and support to open a new issue continuing and finalising the above activities with a more comprehensive solution, e.g. by utilization of os-migrate.
