### ISSUE TITLE
Build angular application to displaying incidents based view represented by the html prototype

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#366]
Building upon the foundation in #365, we need to add displaying of incidents and components to the status page web application for **unauthenticated visitors**.

The displayed content is displayed in a raw fashion without much styling. This is the variant that shall be available for visually and impaired users or visitors that suffer from lacking fine-motorics.
The styled variant will be built on top and is covered by a separate user story.

## Definition of Ready:

- [x] #365 
- [x] #579

## Definition of Done:

- [ ] There is a web-application that shows incidents and components from a running status-page-api server instance

**Comment by okautz** [comment]
Current developments happen in this PR https://github.com/SovereignCloudStack/status-page-web/pull/10

**Comment by snkaupe** [comment]
Current state: We are rendering the bar graphs successfully, as well as the incident log. Table display is still to be done, but should arrive shortly.

There are a number of outstanding issues/questions:

- Data is currently retrieved from JSON files included in the project directory. This is because, in the local development setup, Cross-Origin Resource Sharing (CORS) doesn't allow us to connect the Angular frontend to the API server also running locally. The reason for that is unknown, given that the API server _should_ be properly configured to avoid this issue. Will confer with @joshuai96 regarding this issue once he's back from his parental leave next week. The suggested workaround with Angular—using the proxy included to circumvent CORS—also didn't work due to the proxy running into an internal error. @scoopex might be able to help with this, should we not be able to solve the problem in the API server. This issue is currently considered as low priority, with implementation of site features being given priority.
- The API server might not yet support scheduling a maintenance session before the fact. It might be possible to insert an incident for a future date (untested), but we would not receive this incident when querying the server for our 90 day range. We might need to add explicit support for this to work. Will need to be discussed with @joshuai96 later.
- We currently do not show the correct status colors in our frontend, that is, the colors used to denote a component being in one of our four defined frontend states: _maintenance_, _operational_, _limited_ and _broken_. This is because there is currently no way to map the server API's equivalent, the `ImpactType`, onto these states. `ImpactType` is a non-finite, user-defined resource, so we may not necessary even know what types of impact a user of the status page may define. Furthermore, the severity of an `ImpactType` might be different from incident to incident, based upon its exact circumstances. As an example, the default configuration of the API server defines the `ImpactType` "Connectivity Problems". This may be a component sporadically being unreachable (status "limited") or a complete failure of the network necessary to reach said component (status "broken"). Proper support will need changes to the API server, another topic to discuss with @joshuai96 upon his return next week.

**Comment by scoopex** [comment]
@snkaupe if you run your API development server on a other URL (hots+domain+protocol) than the frontend the simplest way might be to just add the suitable CORS headers to the responses created by the API server implementation that allow the usage of the resources for your domain.

The headers might look like this
(this is very dirty and should never reach a production system :-))

```
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: *
Access-Control-Allow-Methods: *
```

Another (more complex) way ist to extend the angular development server implementation to forward the API requests of `/api/...` (something like that) to an other system. In that case it will be necessary to write some logic to modify the requests and the responses to/from the api server.
The benefit of that solution is that you can also use a public hosted API server instance.

Just contact me by matrix if we should workout something like that

**Comment by joshuai96** [comment]
@snkaupe

> given that the API server should be properly configured

The configuration for allowed origins in the API must be more specific. Currently it's `[]string{"127.0.0.1", "localhost"}` but should include protocols and ports to properly function. That's an oversight on my end.
For now you can overwrite the `SCS_STATUS_PAGE_CORS_ORIGINS` in `secrets.env` with something like `http://localhost/<your_port>`

**Comment by snkaupe** [comment]
I've just had a short discussion with @joshuai96 concerning any changes we want to perform on the API server and we've reached a satisfying conclusion. Joshua will prepare a MR in the near future with the necessary changes done to the OpenAPI specification, which we will link here. Once reviewed and accepted, he will then implement said changes and I shall adapt the frontend.

**Comment by joshuai96** [comment]
As mentioned previously I opened two PRs:

- SovereignCloudStack/standards#498 for documentation
- SovereignCloudStack/status-page-openapi#12 and API spec extension

These are now open for discussion and feel free to do so ;)

**Comment by joshuai96** [comment]
Further work on the API part of severities is now tracked in #579

**Comment by joshuai96** [comment]
@snkaupe severities are done :+1:
