### ISSUE TITLE
Evaluate component(s) that serve as authorization and authentication component in the policy layer

### ISSUE THREAD

**Issue by fkr** [SovereignCloudStack/issues#377]
Since we ditched the idea of using caddy with caddy security, we need to evaluate other components to serve as the component on the policy layer for authorization and authentication.

## Options:

- [ ] dexidp (https://dexidp.io/) with caddy + JWT Plugin
- [x] dexidp + Oathkeeper (https://www.ory.sh/oathkeeper/)

## Definition of Done:

- [x] We have a clue what to use for the policy layer and have tried it out in a PoC

**Comment by joshuai96** [comment]
dex as intermediate IdP between GitHub and the application could be configured for organization access by switching to a organization level  OAuth app.

Caddy with [Caddy Security formerly AuthP](https://authp.github.io/)  did not seem to provide the needed functionality within in a reasonable level of complexity.

Oathkeeper seems to easily validate the JWT provided by dex, but Oathkeepers authors (Ory) have decided to split the decission making of AuthZ to other services. Oathkeeper can validate a JWT, but can not decide on values from the JWT.

The [authorizers](https://www.ory.sh/docs/oathkeeper/pipeline/authz) allow to deny or allow on a valid JWT, while the [JWT authenticator](https://www.ory.sh/docs/oathkeeper/pipeline/authn#jwt) can validate on the claims `iss`, `aud` and possible `scopes` while dex provides a `group` claim providing the users organizations.

[Ory/Keto](https://github.com/ory/keto) is the provided decission sevice that can provide extended decision making.

Another solution for the concrete use case of GitHub as upstream IdP is the use of dex [GitHub connector](https://dexidp.io/docs/connectors/github/#configuration) setting `orgs`. This enabled dex to deny the creation of a JWT if the user isn't part of a specific organization. 
This could be leveraged to rely on Oathkeepers JWT validation, because only organization members could retrieve a valid JWT.
