### ISSUE TITLE
Update Keycloak to version 22

### ISSUE THREAD

**Issue by reqa** [SovereignCloudStack/issues#413]
As a SCS operator, I want to run an up to date version of services so that my installation is secure.

Since https://github.com/osism/ansible-collection-services/pull/1111 SCS runs Keycloak version 19, which has seen a couple of security related updates. We should update to Keycloak 22.x (at time of writing).

## Definition of Ready:

- [ ] User Story is small enough to be finished within one sprint
- [ ] User Story is clear and understood by the whole team
- [ ] Acceptance criteria are defined
- [ ] Acceptance criteria are clear and understood by the whole team

## Definition of Done:

- [ ] All acceptance criteria are met
- [ ] Changes have been reviewed
- [ ] CI tests have run successfully
- [ ] Documentation has been updated
- [ ] Release Notes have been updated

**Comment by bitkeks** [comment]
@reqa according to https://github.com/osism/ansible-collection-services/blob/a5ad87661069d2b69ff90aa8ad43dcdf444c996f/roles/keycloak/defaults/main.yml (current main branch), OSISM ansible-collection-services currently deploys `keycloak_image_tag: "23.0.6"`. 

This issue is therefore outdated and can be closed, right? - please feel free to re-open it in case I missed something.
