### ISSUE TITLE
[Standardization] K8s cluster baseline security setup (previous: KaaS Increased security setups)

### ISSUE THREAD

**Issue by cah-hbaum** [SovereignCloudStack/issues#415]
This issue was created to provide a discussion ground for possible future standards. It is derived from #181 and on of the points not assigned any issue yet.
The following topics/ideas should be discussed and maybe extended:
* external CA
* protected kubeAPI
* security patching for nodes (?)

---

## Definition of Done:

- [ ] Conclusions are reached about all discussion topics
- [ ] A new issue for the creation of a standard (proposal) is created

**Comment by cah-hbaum** [comment]
Some initial notes on these topics in order to create a better document later.

---

**external CA**
* https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/
Increase in complexity but more control due to (probable) self-management of CA as well as CSRs.

**protected kubeAPI*
Theres more to this than just protecting the `kubeAPI`, if a high security setup should be achieved. The API itself as well as the underlying `kubelet` and several other components need to be secured, otherwise a setup could include security risks unknown to its user(s).
Some general sources can be found here:
* https://kubernetes.io/docs/tasks/administer-cluster/securing-a-cluster/
* https://kubernetes.io/docs/concepts/security/controlling-access/
* https://kubernetes.io/docs/reference/access-authn-authz/kubelet-authn-authz/
* https://kubernetes.io/docs/reference/access-authn-authz/authentication/
* https://cheatsheetseries.owasp.org/cheatsheets/Kubernetes_Security_Cheat_Sheet.html (external)

The general advice from these pages can be summed up as follows:
* secure endpoints with TLS
* use authentication and authorization; important, since some components just expose themselves with anonymous requests automatically allowed
* control container runtime privileges
* secure default ports from external access

Protocol | Port Range | Purpose
-- | -- | --
TCP | 6443- | Kubernetes API Server
TCP | 2379-2380 | etcd server client API
TCP | 10250 | Kubelet API
TCP | 10251 | kube-scheduler
TCP | 10252 | kube-controller-manager
TCP | 10255 | Read-Only Kubelet API


Protocol | Port Range | Purpose
-- | -- | --
TCP | 10250 | Kubelet API
TCP | 10255 | Read-Only Kubelet API
TCP | 30000-32767 | NodePort Services

**security patching for nodes**
Depends on what exactly was meant here. Generally, security patches should applied regularly as fast as possible. Personally, I can't imagine a scenario, where only a small portion of nodes of a cluster should be updated (instead of just the whole cluster).

**Comment by cah-hbaum** [comment]
After discussion in the MR, this is renamed to baseline security setup.

**Comment by artificial-intelligence** [comment]
So in the PR there was some generic criticism, that this is not possible to implement in unmentioned specific scenarios for unspecified reasons and I was asked to put my reply into this issue instead of the PR, which I'm doing via this message:

I think for this kind of criticism to be valid, it needs to be precise and concrete to be able to be taken into account.

So it might very well be that there are valid scenarios for which this baseline security causes issues.

But I think they need to be spelled out exactly and it must be shown why exactly this is a problem, so we can either work on improving the situation for these deployments to have better security or exclude these specific scenarios from this standard, for precise reasons.

HTH
