### ISSUE TITLE
[Testing] Tests for K8s cluster hardening

### ISSUE THREAD

**Issue by cah-hbaum** [SovereignCloudStack/issues#670]
Since https://github.com/SovereignCloudStack/standards/issues/475 is done for now, a new issue for the corresponding test is necessary.

## Definition of Done:

- [ ] Test is written
- [ ] Changes have been reviewed
- [ ] PR is merged

**Comment by michal-gubricky** [comment]
### Summary of Work Done on Issue #670:

- **Documentation Review**: Reviewed [Sonobouy DR](https://github.com/SovereignCloudStack/standards/blob/main/Standards/scs-0200-v1-using-sonobuoy-for-kaas-conformance-tests.md) to understand its functionalities.
- **Compliance Testing**: Attempted to run existing compliance tests against the spawned Kubernetes cluster.
- **Plugin Familiarization**: Familiarized with creating plugins for Sonobouy and explored example frameworks.
- **Cluster Setup and Debugging**: Trying to spawn a Yaook k8s cluster, encountering IPv4/IPv6 configuration bugs and Ansible failures during the environment setup, after debugging with the C&H team on Element chat we find out that via the current Yaook k8s project is unable to spawn fully functional cluster since it is not compatible with neutron OVN from OpenStack.
- **Test Development**: Developed tests based on standards, including reading Kubelet configurations.
- **Pod Security Tests**: Implemented tests for the Pod Security Admission Controller across different Kubernetes versions and against a Kind cluster.
- **Authorization Testing**: Created tests for various authorization methods within the Kubernetes cluster.
- **Authentication Investigation**: Investigated authentication methods to develop comprehensive tests.
- **ETCD Testing**: Rewrote tests for ETCD to align with cluster hardening standards.
- **Code Refactoring**: Refactored test code for improved clarity and maintainability.
- **Final Testing**: Conducted final tests against the Kubernetes cluster on GX-SCS to ensure readiness for review.


all the above have been addressed in PR https://github.com/SovereignCloudStack/standards/pull/759
